### ISSUE TITLE
Invalid zip file format

### ISSUE THREAD

**Issue by danielehrhardt** [ianmacd/multidisabler-g97x#10]
I try to flash the v3.0. 
```
Checking for Digest file ...
Unmounting System...
Invalid zip file format!
Error installing zip file 
```
Device: T510
Recovery: Magisk

**Comment by ianmacd** [comment]
Strange. Do you have zip file verification turned on?

If not, let me know the MD5 sum of the zip file.

I have verified that XDA has a good file:

```
[ianmacd@fika ~/src/multidisabler-samsung]$ cmp ../multidisabler-samsung-3.0.zip ~/Downloads/multidisabler-samsung-3.0.zip 
[ianmacd@fika ~/src/multidisabler-samsung]$ md5sum ~/Downloads/multidisabler-samsung-3.0.zip
217197761d5b175ce7e99ff420688d1c */home/ianmacd/Downloads/multidisabler-samsung-3.0.zip
[ianmacd@fika ~/src/multidisabler-samsung]$ unzip -t ~/Downloads/multidisabler-samsung-3.0.zip
Archive:  /home/ianmacd/Downloads/multidisabler-samsung-3.0.zip
    testing: META-INF/                OK
    testing: META-INF/com/            OK
    testing: META-INF/com/google/     OK
    testing: META-INF/com/google/android/   OK
    testing: META-INF/com/google/android/update-binary   OK
No errors detected in compressed data of /home/ianmacd/Downloads/multidisabler-samsung-3.0.zip.
```

**Comment by seupedro** [comment]
I have been facing the same issue. But I think it is caused by MTP corruption when tranfering files from PC.
Downloading direct to external sdcard has no problem for version 3.1.

By the way, thank you for this module!

**Comment by karingoo** [comment]
Hi ianmacd.

Checking for Digest file ...
Unmounting System...
Invalid zip file format!
Error installing zip file 

https://forum.xda-developers.com/t/recovery-root-unofficial-twrp-3-4-0-0-for-galaxy-a50.4138313/page-2
