### ISSUE TITLE
invaild zip file format

### ISSUE THREAD

**Issue by moom825** [ianmacd/multidisabler-g97x#5]
when i go to install it it says invalid file format. im using a samsung a50 please help

**Comment by ianmacd** [comment]
Are you using zip file signature verification in TWRP? If so, turn it off.

**Comment by evren320** [comment]
i have found the download links for multidisabler has zip file has folder META-INF not on the root folder, i have rezipped META-INF and installing that newly created zip worked without errors

**Comment by ianmacd** [comment]
I'm puzzled.

```
[ianmacd@fika /tmp]$ unzip -l =(wget -qO - 'https://forum.xda-developers.com/attachment.php?attachmentid=4991703&d=1586612172')   
Archive:  /tmp/zshk29RxF
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  01-15-2019 11:35   META-INF/
        0  05-30-2018 21:01   META-INF/com/
        0  12-03-2019 12:38   META-INF/com/google/
        0  04-11-2020 11:43   META-INF/com/google/android/
     7458  04-11-2020 11:43   META-INF/com/google/android/update-binary
       28  01-21-2020 14:37   nl
---------                     -------
     7486                     6 files
```

**Comment by bilogic** [comment]
@evren320 is correct, when clicking into the ZIP, I see this

![image](https://user-images.githubusercontent.com/946010/93856751-126f8000-fcec-11ea-8e0b-36787a651e8b.png)

**Comment by bilogic** [comment]
@ianmacd I was using downloads from your github releases here https://github.com/ianmacd/multidisabler-samsung/releases

**Comment by ianmacd** [comment]
> @ianmacd I was using downloads from your github releases here https://github.com/ianmacd/multidisabler-samsung/releases

I didn't know that GitHub was creating a release for each source tag, but in any case, these are not flashable files, because of the extra directory that GitHub creates inside the zip.

**Comment by ianmacd** [comment]
> @evren320 is correct, when clicking into the ZIP, I see this
> 
> ![image](https://user-images.githubusercontent.com/946010/93856751-126f8000-fcec-11ea-8e0b-36787a651e8b.png)

It seems that XDA has an issue and has cached the 2.2 release on some of its servers.

If I refresh the XDA page, the file attached to the first posting in the thread switches between 2.5 (the latest version at the time of writing) and 2.2.

**Comment by bilogic** [comment]
@ianmacd I'm not quite following, but can help verify you are seeing the same issue as @evren320 and me at https://github.com/ianmacd/multidisabler-samsung/releases ?

**Comment by bilogic** [comment]
> I didn't know that GitHub was creating a release for each source tag, but in any case, these are not flashable files, because of the extra directory that GitHub creates inside the zip.

I see, perhaps it can help if that was indicated. I suspect there are folks who trust the GitHub source more than XDA. :)

**Comment by moom825** [comment]
I have fixed my problem but thx
